// Code generated by ent, DO NOT EDIT.

package sink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lbrictson/TinyMonitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// SinkType applies equality check predicate on the "sink_type" field. It's identical to SinkTypeEQ.
func SinkType(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSinkType), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// SinkTypeEQ applies the EQ predicate on the "sink_type" field.
func SinkTypeEQ(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSinkType), v))
	})
}

// SinkTypeNEQ applies the NEQ predicate on the "sink_type" field.
func SinkTypeNEQ(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSinkType), v))
	})
}

// SinkTypeIn applies the In predicate on the "sink_type" field.
func SinkTypeIn(vs ...string) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSinkType), v...))
	})
}

// SinkTypeNotIn applies the NotIn predicate on the "sink_type" field.
func SinkTypeNotIn(vs ...string) predicate.Sink {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSinkType), v...))
	})
}

// SinkTypeGT applies the GT predicate on the "sink_type" field.
func SinkTypeGT(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSinkType), v))
	})
}

// SinkTypeGTE applies the GTE predicate on the "sink_type" field.
func SinkTypeGTE(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSinkType), v))
	})
}

// SinkTypeLT applies the LT predicate on the "sink_type" field.
func SinkTypeLT(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSinkType), v))
	})
}

// SinkTypeLTE applies the LTE predicate on the "sink_type" field.
func SinkTypeLTE(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSinkType), v))
	})
}

// SinkTypeContains applies the Contains predicate on the "sink_type" field.
func SinkTypeContains(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSinkType), v))
	})
}

// SinkTypeHasPrefix applies the HasPrefix predicate on the "sink_type" field.
func SinkTypeHasPrefix(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSinkType), v))
	})
}

// SinkTypeHasSuffix applies the HasSuffix predicate on the "sink_type" field.
func SinkTypeHasSuffix(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSinkType), v))
	})
}

// SinkTypeEqualFold applies the EqualFold predicate on the "sink_type" field.
func SinkTypeEqualFold(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSinkType), v))
	})
}

// SinkTypeContainsFold applies the ContainsFold predicate on the "sink_type" field.
func SinkTypeContainsFold(v string) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSinkType), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sink) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sink) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sink) predicate.Sink {
	return predicate.Sink(func(s *sql.Selector) {
		p(s.Not())
	})
}
