// Code generated by ent, DO NOT EDIT.

package alertchannel

import (
	"time"
)

const (
	// Label holds the string label denoting the alertchannel type in the database.
	Label = "alert_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlertChannelType holds the string denoting the alert_channel_type field in the database.
	FieldAlertChannelType = "alert_channel_type"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMonitors holds the string denoting the monitors edge name in mutations.
	EdgeMonitors = "monitors"
	// Table holds the table name of the alertchannel in the database.
	Table = "alert_channels"
	// MonitorsTable is the table that holds the monitors relation/edge. The primary key declared below.
	MonitorsTable = "alert_channel_monitors"
	// MonitorsInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorsInverseTable = "monitors"
)

// Columns holds all SQL columns for alertchannel fields.
var Columns = []string{
	FieldID,
	FieldAlertChannelType,
	FieldConfig,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// MonitorsPrimaryKey and MonitorsColumn2 are the table columns denoting the
	// primary key for the monitors relation (M2M).
	MonitorsPrimaryKey = []string{"alert_channel_id", "monitor_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
