// Code generated by ent, DO NOT EDIT.

package alertchannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lbrictson/TinyMonitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// AlertChannelType applies equality check predicate on the "alert_channel_type" field. It's identical to AlertChannelTypeEQ.
func AlertChannelType(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAlertChannelType), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// AlertChannelTypeEQ applies the EQ predicate on the "alert_channel_type" field.
func AlertChannelTypeEQ(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeNEQ applies the NEQ predicate on the "alert_channel_type" field.
func AlertChannelTypeNEQ(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeIn applies the In predicate on the "alert_channel_type" field.
func AlertChannelTypeIn(vs ...string) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAlertChannelType), v...))
	})
}

// AlertChannelTypeNotIn applies the NotIn predicate on the "alert_channel_type" field.
func AlertChannelTypeNotIn(vs ...string) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAlertChannelType), v...))
	})
}

// AlertChannelTypeGT applies the GT predicate on the "alert_channel_type" field.
func AlertChannelTypeGT(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeGTE applies the GTE predicate on the "alert_channel_type" field.
func AlertChannelTypeGTE(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeLT applies the LT predicate on the "alert_channel_type" field.
func AlertChannelTypeLT(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeLTE applies the LTE predicate on the "alert_channel_type" field.
func AlertChannelTypeLTE(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeContains applies the Contains predicate on the "alert_channel_type" field.
func AlertChannelTypeContains(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeHasPrefix applies the HasPrefix predicate on the "alert_channel_type" field.
func AlertChannelTypeHasPrefix(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeHasSuffix applies the HasSuffix predicate on the "alert_channel_type" field.
func AlertChannelTypeHasSuffix(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeEqualFold applies the EqualFold predicate on the "alert_channel_type" field.
func AlertChannelTypeEqualFold(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAlertChannelType), v))
	})
}

// AlertChannelTypeContainsFold applies the ContainsFold predicate on the "alert_channel_type" field.
func AlertChannelTypeContainsFold(v string) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAlertChannelType), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AlertChannel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// HasMonitors applies the HasEdge predicate on the "monitors" edge.
func HasMonitors() predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MonitorsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MonitorsTable, MonitorsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonitorsWith applies the HasEdge predicate on the "monitors" edge with a given conditions (other predicates).
func HasMonitorsWith(preds ...predicate.Monitor) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MonitorsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MonitorsTable, MonitorsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		p(s.Not())
	})
}
