// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/TinyMonitor/ent/predicate"
	"github.com/lbrictson/TinyMonitor/ent/sink"
)

// SinkUpdate is the builder for updating Sink entities.
type SinkUpdate struct {
	config
	hooks    []Hook
	mutation *SinkMutation
}

// Where appends a list predicates to the SinkUpdate builder.
func (su *SinkUpdate) Where(ps ...predicate.Sink) *SinkUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SinkUpdate) SetCreatedAt(t time.Time) *SinkUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SinkUpdate) SetNillableCreatedAt(t *time.Time) *SinkUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SinkUpdate) SetUpdatedAt(t time.Time) *SinkUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetSinkType sets the "sink_type" field.
func (su *SinkUpdate) SetSinkType(s string) *SinkUpdate {
	su.mutation.SetSinkType(s)
	return su
}

// SetConfig sets the "config" field.
func (su *SinkUpdate) SetConfig(m map[string]interface{}) *SinkUpdate {
	su.mutation.SetConfig(m)
	return su
}

// Mutation returns the SinkMutation object of the builder.
func (su *SinkUpdate) Mutation() *SinkMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SinkUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	su.defaults()
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SinkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SinkUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SinkUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SinkUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SinkUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := sink.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SinkUpdate) check() error {
	if v, ok := su.mutation.SinkType(); ok {
		if err := sink.SinkTypeValidator(v); err != nil {
			return &ValidationError{Name: "sink_type", err: fmt.Errorf(`ent: validator failed for field "Sink.sink_type": %w`, err)}
		}
	}
	return nil
}

func (su *SinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sink.Table,
			Columns: sink.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: sink.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(sink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(sink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.SinkType(); ok {
		_spec.SetField(sink.FieldSinkType, field.TypeString, value)
	}
	if value, ok := su.mutation.Config(); ok {
		_spec.SetField(sink.FieldConfig, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SinkUpdateOne is the builder for updating a single Sink entity.
type SinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SinkMutation
}

// SetCreatedAt sets the "created_at" field.
func (suo *SinkUpdateOne) SetCreatedAt(t time.Time) *SinkUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SinkUpdateOne) SetNillableCreatedAt(t *time.Time) *SinkUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SinkUpdateOne) SetUpdatedAt(t time.Time) *SinkUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetSinkType sets the "sink_type" field.
func (suo *SinkUpdateOne) SetSinkType(s string) *SinkUpdateOne {
	suo.mutation.SetSinkType(s)
	return suo
}

// SetConfig sets the "config" field.
func (suo *SinkUpdateOne) SetConfig(m map[string]interface{}) *SinkUpdateOne {
	suo.mutation.SetConfig(m)
	return suo
}

// Mutation returns the SinkMutation object of the builder.
func (suo *SinkUpdateOne) Mutation() *SinkMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SinkUpdateOne) Select(field string, fields ...string) *SinkUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sink entity.
func (suo *SinkUpdateOne) Save(ctx context.Context) (*Sink, error) {
	var (
		err  error
		node *Sink
	)
	suo.defaults()
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SinkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Sink)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SinkMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SinkUpdateOne) SaveX(ctx context.Context) *Sink {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SinkUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SinkUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SinkUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := sink.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SinkUpdateOne) check() error {
	if v, ok := suo.mutation.SinkType(); ok {
		if err := sink.SinkTypeValidator(v); err != nil {
			return &ValidationError{Name: "sink_type", err: fmt.Errorf(`ent: validator failed for field "Sink.sink_type": %w`, err)}
		}
	}
	return nil
}

func (suo *SinkUpdateOne) sqlSave(ctx context.Context) (_node *Sink, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sink.Table,
			Columns: sink.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: sink.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sink.FieldID)
		for _, f := range fields {
			if !sink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(sink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(sink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.SinkType(); ok {
		_spec.SetField(sink.FieldSinkType, field.TypeString, value)
	}
	if value, ok := suo.mutation.Config(); ok {
		_spec.SetField(sink.FieldConfig, field.TypeJSON, value)
	}
	_node = &Sink{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
