// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AlertChannel is the predicate function for alertchannel builders.
type AlertChannel func(*sql.Selector)

// Monitor is the predicate function for monitor builders.
type Monitor func(*sql.Selector)

// Secret is the predicate function for secret builders.
type Secret func(*sql.Selector)

// Sink is the predicate function for sink builders.
type Sink func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
